### ISSUE TITLE
crast

### ISSUE THREAD

**Issue by caspervanneck** [GMNetwork/TF-Auth#1]
Notice: Undefined variable: index in phar://C:/Users/Wesleyvanneck/Desktop/genisys/ClearSky.phar/src/pocketmine/network/protocol/LoginPacket.php on line 54

Fatal error: Uncaught Error: Cannot use object of type stdClass as array in phar://C:/Users/Wesleyvanneck/Desktop/genisys/ClearSky.phar/src/pocketmine/network/protocol/LoginPacket.php:54
Stack trace:
#0 phar://C:/Users/Wesleyvanneck/Desktop/genisys/ClearSky.phar/src/pocketmine/network/Network.php(220): pocketmine\network\protocol\LoginPacket->decode()
#1 phar://C:/Users/Wesleyvanneck/Desktop/genisys/ClearSky.phar/src/pocketmine/Player.php(1984): pocketmine\network\Network->processBatch(Object(pocketmine\network\protocol\BatchPacket), Object(pocketmine\Player))
#2 phar://C:/Users/Wesleyvanneck/Desktop/genisys/ClearSky.phar/src/pocketmine/network/RakLibInterface.php(140): pocketmine\Player->handleDataPacket(Object(pocketmine\network\protocol\BatchPacket))
#3 phar://C:/Users/Wesleyvanneck/Desktop/genisys/ClearSky.phar/src/raklib/server/ServerHandler.php(78): pocketmine\network\RakLibInterface->handleEncapsulated('192.168.178.43:...', Object(raklib\protocol\EncapsulatedPacket), 0)
#4 phar://C:/Users/Wesleyvanneck/Desktop/geni in phar://C:/Users/Wesleyvanneck/Desktop/genisys/ClearSky.phar/src/pocketmine/network/protocol/LoginPacket.php on line 54

ClearSky Crash Dump Sun Aug 21 11:55:24 BST 2016

Error: Uncaught Error: Cannot use object of type stdClass as array in phar://C:/Users/Wesleyvanneck/Desktop/genisys/ClearSky.phar/src/pocketmine/network/protocol/LoginPacket.php:54
File: /src/pocketmine/network/protocol/LoginPacket
Line: 54
Type: E_ERROR

Code:
[45] 					if($webtoken["identityPublicKey"] != self::MOJANG_PUBKEY) $chainKey = $webtoken["identityPublicKey"];
[46] 					break;
[47] 				}elseif($chainKey === null){
[48] 					break;
[49] 				}
[50] 			}
[51] 			if(!$verified && $chainKey !== null){
[52] 				$chainKey = null;
[53] 			}else{
[54] 				unset($chainData[$index]);
[55] 			}
[56] 		}
[57] 		list($verified, $skinToken) = $this->decodeToken($this->get($this->getLInt()), $chainKey);
[58] 		
[59] 		if(isset($skinToken["ClientRandomId"])){
[60] 			$this->clientId = $skinToken["ClientRandomId"];
[61] 		}
[62] 		if(isset($skinToken["ServerAddress"])){
[63] 			$this->serverAddress = $skinToken["ServerAddress"];
[64] 		}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #227 [Protocol 82; API 2.0.0]
uname -a: Windows NT DELL-PC 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) AMD64
PHP Version: 7.0.10

**Comment by SalmonGER** [comment]
Uhm I'm afraid this is a ClearSky Issue

**Comment by caspervanneck** [comment]
yes i know now

**Comment by Aericio** [comment]
Need to wait for them to push their xboxauth branch to master

**Comment by SalmonGER** [comment]
@Aericio actually the issue above is caused by the xbox-auth branch. php7 branch works fine

**Comment by Aericio** [comment]
@SalmonGER Exactly what I mean...
